revision=v1.3.8
crc=1289992789
url=https://gcache.2005.rs/code/
main-class=game.swing.Launcher
lib=false
natives=false

# Public client connection settings.
connection-mode=management
management-scheme=http
management-host=80.56.247.15
management-port=43591
preferred-world=54
dev=false

