revision=v1.4
crc=3364530959
url=https://gcache.2005.rs/code/
main-class=game.swing.Launcher
lib=false
natives=false

# Public client connection settings.
connection-mode=management
management-scheme=http
management-host=80.56.247.15
management-port=43591
