revision=v1.3.8
crc=2467809877
url=https://gcache.2005.rs/code/
main-class=game.swing.Launcher
lib=false
natives=false

# Public client connection settings. Never put internal shared secrets here.
connection-mode=management
management-scheme=http
management-host=http://2005.rs
management-port=43591
preferred-world=37
dev=true

